### ISSUE TITLE
GISCs monitor data availability of data from their AoR

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/monitoring#16]
While GISCs are not supposed to become monitoring centers, they still play an important role to address issues with data availability for their AoR. Thus, WISMonitoring should become an integral part of GISC Watch and also procedures to address issues need to be defined. In principle GISCs can become sensor centers sharing their view in respect for their AoR

**Comment by kurt-hectic** [comment]
Manual on WIS already requires GISCs to monitor their AoR.
Not in scope for new monitoring.
GISCs can avail themselves of the new monitoring the complement their own monitoring.
