### ISSUE TITLE
Decode BUFR data

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/monitoring#26]
A monitoring center needs to be able to decode BUFR data with and without WIGOS Station Identifiers

**Comment by EgawaTakumu** [comment]
In my opinion,  a monitoring center needs to keep up with the updates of BUFR table.

The latest version is 37 as of November 2021.
  https://community.wmo.int/activity-areas/wis/latest-version
It is updated several times a year. 
  https://community.wmo.int/activity-areas/wis/previous-versions

**Comment by kaiwirt** [comment]
Data is to be decoded at sensor centers.
