### ISSUE TITLE
Sensor centers send raw data to the monitoring centers

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/monitoring#8]
Sensor centers should not need to process the data for the monitoring. This task should be done by the monitoring centers. It is much easier if sensor centers only forward what they see.

**Comment by czanna** [comment]
at acquisition/preprocessing stage we systematically compute SQL based reports that may include different metrics and grouping criteria ( eg based on last n-hours of ingested data) 

_count
n.files/n.bullettins/n.subsets, data volumes(KB), timeliness(minutes) 
group by
data_source (eg egrr,edzw), GTS AHL, BUFR dataCategory/SubCategory,  StationID, WMO Block, Country , Ingestion time Interval (1h, 6h, 24h)_

The aim is to produce time series, interactive maps and trigger automatic alarms  when "relevant"  anomalies ( eg obsType outage ) are found

**Comment by kaiwirt** [comment]
Related to #11

**Comment by kaiwirt** [comment]
Agreed by TT-WIS-MON 03/21
